# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example Piantor Pro'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["beekeeb/piantor_pro"]'
      merge: '["qmk/qmk_firmware/master"]'
